title: "ORNL Theme for Jekyll"
author: "Greg Watson <watsongr@ornl.gov>"
description: "ORNL Jekyll Template"

# Correct linking GitHub Project pages
# Note leading slash in baseurl
githubrepo: Jekyll-ORNL-Theme
baseurl: /Jekyll-ORNL-Theme

permalink: pretty

kramdown:
  auto_ids: true
